# False: no cropping and the whole cloud will be published
# True: min max values provided will be used
bool enable_cropping

# False: no filtering
# True: Removes points so that the dencity is 1p/cm^3
bool enable_voxel_filter 

# Values for boxfilter in camera frame
float64 min_x
float64 min_y
float64 min_z

float64 max_x
float64 max_y
float64 max_z

---
